spring.application.name=library

logging.level.com.homework.library.service=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [traceId=%X{traceId} spanId=%X{spanId}] %logger{36} - %msg%n
logging.level.org.hibernate.SQL=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics
management.opentelemetry.resource-attributes.service.name=library-service
management.observations.annotations.enabled=true
management.tracing.sampling.probability=1.0