CREATE TABLE borrowers
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower VARCHAR(255) NOT NULL
);

CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    author      VARCHAR(255) NOT NULL,
    borrower_id BIGINT,
    CONSTRAINT fk_book_borrower
        FOREIGN KEY (borrower_id)
        REFERENCES borrowers (id)
);
